version: '3'
services:
  input_service:
    build: ./input
    ports:
      - "5000:5000"
    depends_on:
      - processing

  processing_service:
    build: ./processing
    ports:
      - "5001:5001"
    depends_on:
      - output

  output_service:
    build: ./output
    ports:
      - "5002:5002"
